ui: mocha-bdd
browsers:
  - name: chrome
    version: -2..latest
  - name: safari
    version: -2..latest
  - name: firefox
    version: -2..latest
  - name: iphone
    version: [7.0, 8.0, 9.0, latest]
  - name: internet explorer
    version: 10..latest
  - name: microsoftedge
    version: latest
  - name: opera
    version: latest
  - name: android
    version: '4.4..latest'
